force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <label>Comment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment__c/fields/Comment_Text__c.field-meta.xml
<CustomField>
    <fullName>Comment_Text__c</fullName>
    <label>Comment Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Idea__c.field-meta.xml
<CustomField>
    <fullName>Idea__c</fullName>
    <label>Idea</label>
    <referenceTo>Idea__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Idea__c/Idea__c.object-meta.xml
<CustomObject>
    <label>Idea</label>
    <nameField>
        <label>Idea Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ideas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Idea__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bugs</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Sales/Opportunities</fullName>
            </value>
            <value>
                <fullName>UI</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>AI Marketing Agent</fullName>
            </value>
            <value>
                <fullName>MarTech</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Idea_Space__c.field-meta.xml
<CustomField>
    <fullName>Idea_Space__c</fullName>
    <label>Idea Space</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IdeaForge</fullName>
            </value>
            <value>
                <fullName>OneAlgorithm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ideation</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
            </value>
            <value>
                <fullName>In Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Votes__c.field-meta.xml
<CustomField>
    <fullName>Votes__c</fullName>
    <label>Votes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Idea_Space__c/Idea_Space__c.object-meta.xml
<CustomObject>
    <label>Idea Space</label>
    <nameField>
        <label>Idea Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Idea Spaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote__c/Vote__c.object-meta.xml
<CustomObject>
    <label>Vote</label>
    <nameField>
        <label>Vote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote__c/fields/Idea__c.field-meta.xml
<CustomField>
    <fullName>Idea__c</fullName>
    <label>Idea</label>
    <referenceTo>Idea__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vote__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Votes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vote__c/fields/Vote_Type__c.field-meta.xml
<CustomField>
    <fullName>Vote_Type__c</fullName>
    <label>Vote Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Up</fullName>
            </value>
            <value>
                <fullName>Down</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OverviewController.cls
public with sharing class OverviewController {

    @AuraEnabled(cacheable=true)
    public static List<Idea__c> getIdeas() {

        return [

            SELECT
                Id,
                Name,
                Description__c,
                Category__c,
                Status__c,
                Votes__c,
                Idea_Space__c,
                CreatedDate,
                CreatedById,
                CreatedBy.Name,
                (SELECT Id FROM Comments__r)

            FROM Idea__c

            ORDER BY CreatedDate DESC
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Comment__c> getComments(
        Id ideaId
    ) {

        return [

            SELECT
                Id,
                Comment_Text__c,
                CreatedDate,
                CreatedBy.Name

            FROM Comment__c

            WHERE Idea__c = :ideaId

            ORDER BY CreatedDate DESC
        ];
    }

    @AuraEnabled
    public static void saveComment(
        Id ideaId,
        String commentText
    ) {

        Comment__c newComment =
            new Comment__c();

        newComment.Idea__c =
            ideaId;

        newComment.Comment_Text__c =
            commentText;

        insert newComment;
    }

    @AuraEnabled
    public static Integer upvoteIdea(
        Id ideaId
    ) {

        Id currentUserId =
            UserInfo.getUserId();

        List<Vote__c> existingVotes = [

            SELECT
                Id,
                Vote_Type__c

            FROM Vote__c

            WHERE Idea__c = :ideaId
            AND User__c = :currentUserId

            LIMIT 1
        ];

        if(
            !existingVotes.isEmpty()
            &&
            existingVotes[0].Vote_Type__c ==
            'Upvote'
        ){

            Idea__c existingIdea = [

                SELECT Votes__c

                FROM Idea__c

                WHERE Id = :ideaId

                LIMIT 1
            ];

            return Integer.valueOf(
                existingIdea.Votes__c
            );
        }

        if(!existingVotes.isEmpty()){

            existingVotes[0].Vote_Type__c =
                'Upvote';

            update existingVotes[0];

        } else {

            Vote__c vote =
                new Vote__c();

            vote.Idea__c =
                ideaId;

            vote.User__c =
                currentUserId;

            vote.Vote_Type__c =
                'Upvote';

            insert vote;
        }

        Integer total = 0;

        List<Vote__c> allVotes = [

            SELECT Vote_Type__c

            FROM Vote__c

            WHERE Idea__c = :ideaId
        ];

        for(
            Vote__c v :
            allVotes
        ){

            if(
                v.Vote_Type__c ==
                'Upvote'
            ){

                total++;

            }
            else if(
                v.Vote_Type__c ==
                'Downvote'
            ){

                total--;

            }
        }

        Idea__c idea = [

            SELECT
                Id,
                Votes__c

            FROM Idea__c

            WHERE Id = :ideaId

            LIMIT 1
        ];

        idea.Votes__c =
            total;

        update idea;

        return total;
    }

    @AuraEnabled
    public static Integer downvoteIdea(
        Id ideaId
    ) {

        Id currentUserId =
            UserInfo.getUserId();

        List<Vote__c> existingVotes = [

            SELECT
                Id,
                Vote_Type__c

            FROM Vote__c

            WHERE Idea__c = :ideaId
            AND User__c = :currentUserId

            LIMIT 1
        ];

        if(
            !existingVotes.isEmpty()
            &&
            existingVotes[0].Vote_Type__c ==
            'Downvote'
        ){

            Idea__c existingIdea = [

                SELECT Votes__c

                FROM Idea__c

                WHERE Id = :ideaId

                LIMIT 1
            ];

            return Integer.valueOf(
                existingIdea.Votes__c
            );
        }

        if(!existingVotes.isEmpty()){

            existingVotes[0].Vote_Type__c =
                'Downvote';

            update existingVotes[0];

        } else {

            Vote__c vote =
                new Vote__c();

            vote.Idea__c =
                ideaId;

            vote.User__c =
                currentUserId;

            vote.Vote_Type__c =
                'Downvote';

            insert vote;
        }

        Integer total = 0;

        List<Vote__c> allVotes = [

            SELECT Vote_Type__c

            FROM Vote__c

            WHERE Idea__c = :ideaId
        ];

        for(
            Vote__c v :
            allVotes
        ){

            if(
                v.Vote_Type__c ==
                'Upvote'
            ){

                total++;

            }
            else if(
                v.Vote_Type__c ==
                'Downvote'
            ){

                total--;

            }
        }

        Idea__c idea = [

            SELECT
                Id,
                Votes__c

            FROM Idea__c

            WHERE Id = :ideaId

            LIMIT 1
        ];

        idea.Votes__c =
            total;

        update idea;

        return total;
    }
}