force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <label>Comment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment__c/fields/Comment_Text__c.field-meta.xml
<CustomField>
    <fullName>Comment_Text__c</fullName>
    <label>Comment Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Idea__c.field-meta.xml
<CustomField>
    <fullName>Idea__c</fullName>
    <label>Idea</label>
    <referenceTo>Idea__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Idea__c/Idea__c.object-meta.xml
<CustomObject>
    <label>Idea</label>
    <nameField>
        <label>Idea Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ideas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Idea__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bugs</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Sales/Opportunities</fullName>
            </value>
            <value>
                <fullName>UI</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>AI Marketing Agent</fullName>
            </value>
            <value>
                <fullName>MarTech</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Idea_Space__c.field-meta.xml
<CustomField>
    <fullName>Idea_Space__c</fullName>
    <label>Idea Space</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IdeaForge</fullName>
            </value>
            <value>
                <fullName>OneAlgorithm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ideation</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
            </value>
            <value>
                <fullName>In Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Votes__c.field-meta.xml
<CustomField>
    <fullName>Votes__c</fullName>
    <label>Votes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Idea_Space__c/Idea_Space__c.object-meta.xml
<CustomObject>
    <label>Idea Space</label>
    <nameField>
        <label>Idea Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Idea Spaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OneAlgorithmController.cls
public with sharing class OneAlgorithmController {

    @AuraEnabled(cacheable=true)
    public static List<Idea__c> getIdeas() {

        return [

            SELECT
                Id,
                Name,
                Description__c,
                Category__c,
                Status__c,
                Votes__c,
                Idea_Space__c,
                CreatedDate,
                CreatedById,
                CreatedBy.Name,
                (SELECT Id FROM Comments__r)

            FROM Idea__c

            WHERE Idea_Space__c = 'OneAlgorithm'

            ORDER BY CreatedDate DESC
        ];
    }

    @AuraEnabled
    public static void saveIdea(
        String title,
        String description,
        String category
    ) {

        Idea__c idea = new Idea__c();

        idea.Name = title;
        idea.Description__c = description;
        idea.Category__c = category;
        idea.Status__c = 'Ideation';
        idea.Idea_Space__c = 'OneAlgorithm';
        idea.Votes__c = 0;

        insert idea;
    }

    @AuraEnabled(cacheable=true)
    public static List<Comment__c> getComments(Id ideaId) {

        return [

            SELECT
                Id,
                Comment_Text__c,
                CreatedDate,
                CreatedBy.Name

            FROM Comment__c

            WHERE Idea__c = :ideaId

            ORDER BY CreatedDate DESC
        ];
    }

    @AuraEnabled
    public static void saveComment(
        Id ideaId,
        String commentText
    ) {

        Comment__c commentRecord =
            new Comment__c();

        commentRecord.Idea__c =
            ideaId;

        commentRecord.Comment_Text__c =
            commentText;

        insert commentRecord;
    }

    @AuraEnabled
    public static Integer upvoteIdea(
        Id ideaId
    ) {

        Idea__c idea = [

            SELECT
                Id,
                Votes__c

            FROM Idea__c

            WHERE Id = :ideaId

            LIMIT 1
        ];

        if(idea.Votes__c == null){

            idea.Votes__c = 0;

        }

        idea.Votes__c =
            idea.Votes__c + 10;

        update idea;

        return Integer.valueOf(
            idea.Votes__c
        );
    }

    @AuraEnabled
    public static Integer downvoteIdea(
        Id ideaId
    ) {

        Idea__c idea = [

            SELECT
                Id,
                Votes__c

            FROM Idea__c

            WHERE Id = :ideaId

            LIMIT 1
        ];

        if(idea.Votes__c == null){

            idea.Votes__c = 0;

        }

        idea.Votes__c =
            idea.Votes__c - 10;

        update idea;

        return Integer.valueOf(
            idea.Votes__c
        );
    }

    @AuraEnabled(cacheable=true)
    public static Integer getIdeationCount() {

        return [

            SELECT Count()

            FROM Idea__c

            WHERE Idea_Space__c = 'OneAlgorithm'
            AND Status__c = 'Ideation'
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Integer getDevelopmentCount() {

        return [

            SELECT Count()

            FROM Idea__c

            WHERE Idea_Space__c = 'OneAlgorithm'
            AND Status__c = 'In Development'
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Integer getProductionCount() {

        return [

            SELECT Count()

            FROM Idea__c

            WHERE Idea_Space__c = 'OneAlgorithm'
            AND Status__c = 'In Production'
        ];
    }

}