force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Cover_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Cover_Image_URL__c</fullName>
    <label>Cover Image URL</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Date_Time__c</fullName>
    <label>Event Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Description__c.field-meta.xml
<CustomField>
    <fullName>Event_Description__c</fullName>
    <label>Event Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Poll</fullName>
            </value>
            <value>
                <fullName>Challenge</fullName>
            </value>
            <value>
                <fullName>Hackathon</fullName>
            </value>
            <value>
                <fullName>Announcement</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Workshop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Vote_Count__c.field-meta.xml
<CustomField>
    <fullName>Vote_Count__c</fullName>
    <label>Vote Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EventController.cls
public with sharing class EventController {

    @AuraEnabled(cacheable=true)
    public static List<Event__c> getEvents() {

        return [

            SELECT
                Id,
                Name,
                Event_Type__c,
                Event_Description__c,
                Event_Date_Time__c,
                Event_Location__c,
                Status__c,
                Vote_Count__c,
                Cover_Image_URL__c,
                CreatedDate,
                CreatedBy.Name

            FROM Event__c

            ORDER BY CreatedDate DESC
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Event__c getEventDetails(Id eventId){

        return [

            SELECT
                Id,
                Name,
                Event_Type__c,
                Event_Description__c,
                Event_Date_Time__c,
                Event_Location__c,
                Status__c,
                Vote_Count__c,
                //Cover_Image_URL__c,
                CreatedBy.Name

            FROM Event__c

            WHERE Id = :eventId
            LIMIT 1
        ];
    }

    @AuraEnabled
    public static Id createEvent(

        String title,
        String description,
        String eventType,
        String location,
        String eventDateTime,
        String imageUrl

    ){

        try{

            Event__c ev = new Event__c();

            ev.Name = title;
            ev.Event_Description__c = description;
            ev.Event_Type__c = eventType;
            ev.Event_Location__c = location;

            if(String.isNotBlank(eventDateTime)){

                ev.Event_Date_Time__c =
                    Datetime.valueOf(
                        eventDateTime
                            .replace('T',' ')
                            .replace('Z','')
                    );
            }

            ev.Cover_Image_URL__c = imageUrl;
            ev.Status__c = 'Active';
            ev.Vote_Count__c = 0;

            insert ev;

            return ev.Id;

        }catch(Exception e){

            throw new AuraHandledException(
                'Error Creating Event : ' +
                e.getMessage()
            );

        }
    }

    @AuraEnabled
    public static Integer upVote(Id eventId){

        Event__c ev = [

            SELECT
                Id,
                Vote_Count__c

            FROM Event__c

            WHERE Id = :eventId
            LIMIT 1
        ];

        if(ev.Vote_Count__c == null){

            ev.Vote_Count__c = 0;
        }

        ev.Vote_Count__c++;

        update ev;

        return Integer.valueOf(
            ev.Vote_Count__c
        );
    }

    @AuraEnabled
    public static Integer downVote(Id eventId){

        Event__c ev = [

            SELECT
                Id,
                Vote_Count__c

            FROM Event__c

            WHERE Id = :eventId
            LIMIT 1
        ];

        if(ev.Vote_Count__c == null){

            ev.Vote_Count__c = 0;
        }

        if(ev.Vote_Count__c > 0){

            ev.Vote_Count__c--;
        }

        update ev;

        return Integer.valueOf(
            ev.Vote_Count__c
        );
    }

}